### PR TITLE
feat: Add MissinNumber problem solution in CSES Folder

### PR DESCRIPTION
**Pull request by Als1510**

### CODE REVIEW

**Comment by cheemsjs** [comment]
Contribute here : https://github.com/cheemsjs/hacktoberfest-22

**Comment by PraSarOG** [comment]
Please give a star!

**Comment by Als1510** [comment]
Hi PraSarOG Does that repository not accept the contributions?

**Comment by Als1510** [comment]
Yeah, Contributed in cheemsjs.

**Pull request merged**
