### PR TITLE
added-Expense-Tracker-using-React.js

### PR DESCRIPTION
**Pull request by Eli4479**
I have added a Expense tracker application which is coded in react. this is for the hacktober fest.

### CODE REVIEW

**Review by PraSarOG — COMMENTED** [review]
Where is your code?

**Comment by Eli4479** [comment]
> Where is your code?

I have added a subfolder with the name "Expense-Tracker" in the repo.

here is the photo of the same
Screenshot from 2022-10-01 23-58-29

**Comment by PraSarOG** [comment]
okay

**Comment by PraSarOG** [comment]
Please give a star!

**Comment by PraSarOG** [comment]
Can you open the folder, because I am not able to do so

**Comment by Eli4479** [comment]
> Can you open the folder because I am not able to do so

Yes,Sir I can open the folder

**Comment by PraSarOG** [comment]
uhh! leave it

**Comment by Eli4479** [comment]
> are u from IIT BHU?

YES sir.

**Comment by PraSarOG** [comment]
lol saw the COPS repo in your profile

**Comment by ayushkedia05** [comment]
can you assign this issue to me

**Pull request merged**
